/* ===================================================================
   AYBARS PETSHOP - 222 URUNLUK RESMI KATALOG LISTESI
   =================================================================== */

window.catalogProducts = [
  { id: 1, name: "Royalist Pudra Kokulu Yavru Köpek Şampuanı", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 2, name: "Dreamies Ördekli Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 3, name: "Muhabbet Kuşu Yemi (500 gr)", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 4, name: "Doğal Kuru Yonca (350 gr)", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 5, name: "BioFeline Prebiyotik Deri ve Tüy Destek Kedi Macunu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 6, name: "Royalist Tek Kullanımlık Köpek Külodu (XS - Ekstra Küçük)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 7, name: "NutriSuper Kuş Multivitamini", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 8, name: "Garden Mix Deri Burgu Çubuk Köpek Ödülü (5-100 Adet)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 9, name: "Garden Mix Somon Ezmeli Sıvı Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 10, name: "LuckyPaw Air Mesh Göğüs Tasması (Nefes Alan)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 11, name: "Royal Canin Yavru Kedi Kuru Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 12, name: "Garden Mix Kurutulmuş Köpek Ödülü Dana İşkembe (100 gr)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 13, name: "Garden Mix Paraketler İçin Tam Yem (500 gr)", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 14, name: "Garden Mix Cennet & Sultan Papağan Yemi (500 gr)", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 15, name: "Kiki Excellent Profesyonel Multivitamin Kedi Macunu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 16, name: "Garden Mix Karides Ezmeli Sıvı Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 17, name: "Felicia Hipoalerjenik Somonlu Yetişkin Deri ve Tüy Destekli Kedi Maması (Deneme Ürünü)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 18, name: "Crocus Cat Cream Somonlu & Karidesli Krema Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 19, name: "Crocus Cat Cream Yengeçli Krema Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 20, name: "BioFeline Prebiyotik Yavru Kedi Deri ve Tüy Macunu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 21, name: "BioFeline Prebiyotik Tüy Yumağı Önleyici Malt Macun", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 22, name: "Advance Active Defense Hindili Kısırlaştırılmış Yetişkin Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 23, name: "Garden Mix Kuzu Eti Ezmeli Sıvı Köpek Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 24, name: "Serypet Evcil Hayvan Tüy Toplayıcı", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 25, name: "Garden Mix Somonlu Dolgulu Çıtır Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 26, name: "High-Protein Düğüm Kemik (36 cm, 15 Adet)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 27, name: "High-Protein Preslenmiş Kemik (22 cm)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 28, name: "Royal Canin Starter Anne ve Yavru Köpek Mus Konserve (1-2 Ay)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 29, name: "Garden Mix Ton Balığı Ezmeli Sıvı Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 30, name: "Garden Mix Kanaryalar İçin Tam Yem (500 gr)", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 31, name: "Crocus Cat Cream Ton Balıklı Krema Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 32, name: "Garden Mix Kristal Kedi Kumu", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 33, name: "NaturaPel by Trope Kedi ve Köpek Temizleme Islak Mendili (100 Adet)", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 34, name: "BioFeline Move Glukozamin Eklem Destek Tableti", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 35, name: "BioFeline Microbi Sıvı Probiyotik", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 36, name: "Royalist Tek Kullanımlık Köpek Külodu (M - Orta / L - Büyük)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 37, name: "High-Protein Beyaz Preslenmiş Kemik XL (27 cm)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 38, name: "Advance Active Defense Somonlu Kısırlaştırılmış Yetişkin Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 39, name: "Hill's Science Diet Hassas Sindirim Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 40, name: "Advance Active Defense Tavuklu Küçük Irk Yetişkin Köpek Maması (1-10 kg)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 41, name: "Garden Mix Sığır Derisi Halka Köpek Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 42, name: "Purina Gourmet Gold Hindi Etli Kıyılmış Yaş Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 43, name: "Garden Mix Muhabbet Kuşu Krakeri", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 44, name: "Purina Pro Plan Küçük Irk Somonlu Hassas Deri Yetişkin Köpek Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 45, name: "Pedigree Biscrok Multi Mix Köpek Bisküvisi", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 46, name: "Garden Mix Hamsterlar İçin Tam Yem (1000 gr)", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 47, name: "Büyük Tavşan Yemi (750 gr)", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 48, name: "GimCat Malt-Soft Extra Profesyonel Tüy Yumağı Önleyici Kedi Macunu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 49, name: "GimCat Profesyonel Multivitamin Kedi Macunu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 50, name: "SupraVet Tüy Yumağı Önleyici Yumuşak Kedi Malt Macunu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 51, name: "Garden Mix Yetişkin Muhabbet Kuşları İçin Tam Yem (500 gr)", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 52, name: "Purina Pro Plan Jöleli Hindili Günlük Beslenme Yaş Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 53, name: "Advance Active Defense Somonlu Küçük Irk Hassas Yetişkin Köpek Maması (1-10 kg)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 54, name: "Garden Mix Tavşanlar İçin Tam Yem (1000 gr)", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 55, name: "My Cat Doğal Çam Pelleti Kedi Kumu", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 56, name: "Advance Active Defense Tüy Yumağı ve Kilo Kontrollü Yetişkin Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 57, name: "Purina Gourmet Gold Ton Balıklı Kıyılmış Yaş Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 58, name: "Reflex Soslu Tavuk Parçalı Yavru Kedi Konserve Maması (400 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 59, name: "Quik Tatlı Su Akvaryum Tuzu", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 60, name: "Quik Terry Derma Bit Spreyi (200 ml)", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 61, name: "Quik Banyo Spreyi", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 62, name: "Garden Mix Ton Balıklı & Tavuklu Dolgulu Çıtır Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 63, name: "Felicia Soslu Parçalı Yaş Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 64, name: "Garden Mix Tavuklu Dolgulu Çıtır Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 65, name: "Pro Line Bebek Pudrası Kokulu %100 Doğal Bentonit Kedi Kumu", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 66, name: "Nutri Super Kuş Multivitamini", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 67, name: "Reflex Plus Jöleli Somonlu ve Ton Balıklı Yetişkin Kedi Konservesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 68, name: "Reflex Av Eti ve Kaz Etli Kedi Ödül Çubuğu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 69, name: "Reflex Tavuklu Kedi Ödül Çubuğu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 70, name: "Crocus Cat Cream Karidesli Krema Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 71, name: "Reflex Plus Tahılsız Kuzu Etli Yetişkin Köpek Ödül Çubuğu", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 72, name: "Wanpy Etli Kedi Ödül Çubuğu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 73, name: "Royal Canin Tüy ve Deri Sağlığı Destekli Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 74, name: "BioFeline Balık Yağı Omega 3 ve Omega 6", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 75, name: "BioFeline Prebiyotik Kısırlaştırılmış Kedi Macunu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 76, name: "Reflex Plus Sığır Etli Yetişkin Köpek Ödül Çubuğu", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 77, name: "Fresh Paty Sağlık Göstergeli Kedi Kumu Koku Giderici Deodorant", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 78, name: "Royal Canin Chihuahua Yetişkin Köpek Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 79, name: "Royal Canin Yorkshire Terrier Yetişkin Köpek Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 80, name: "Garden Mix Somonlu & Ördekli Dolgulu Çıtır Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 81, name: "Dreamies Nefis Somon Aromalı Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 82, name: "High-Protein %100 Sığır Doğal Düğüm Çiğneme Kemiği", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 83, name: "Les Repas Plaisir İdrar Yolu Destekli Yaş Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 84, name: "Purina Gourmet Gold Tavuklu Kıyılmış Konserve Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 85, name: "Garden Mix Ton Balıklı Dolgulu Çıtır Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 86, name: "Kiki Excellent Pudra Kokulu Kedi Kumu Koku Giderici", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 87, name: "Wanpy Ton Balığı, Tavuk ve Havuçlu Sıvı Kedi Ödül Ezmesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 88, name: "Dreamies Ördekli Kedi Ödülü (Mavi Paket)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 89, name: "Garden Mix Ördekli Dolgulu Çıtır Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 90, name: "Reflex Plus Soslu Beyaz Etli Balıklı Yetişkin Kedi Konservesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 91, name: "Reflex Plus Jöleli Ton Balıklı ve Alabalıklı Yetişkin Kedi Konservesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 92, name: "Reflex Plus Soslu Kuzu Etli Yetişkin Kedi Konservesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 93, name: "Dreamies Somon Aromalı ve Peynirli Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 94, name: "Pedigree Dentastix Günlük Ağız ve Diş Bakımı Köpek Ödülü (10-25 kg)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 95, name: "Royal Canin Starter Anne ve Yavru Küçük Irk Köpek Maması (10 kg'a kadar)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 96, name: "Akyar Ameliyat Sonrası Kedi Kıyafeti", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 97, name: "Reflex Plus Soslu Tavuklu Yetişkin Kedi Konservesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 98, name: "SupraVet Profesyonel Tüy Yumağı Önleyici Kedi Malt Macunu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 99, name: "Advance Active Defense Somonlu Orta ve Büyük Irk Hassas Köpek Maması (+10 kg)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 100, name: "Pikare Soslu Kuzu Etli Parçalı Yetişkin Köpek Konserve Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 101, name: "Reflex Plus Jöleli Sığır Etli Kısırlaştırılmış Yetişkin Kedi Konservesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 102, name: "Reflex Plus Tahılsız Ördek ve Kaz Etli Kedi Ödül Çubuğu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 103, name: "Felicia Başlangıç Destekli Tavuklu Yavru Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 104, name: "Purina Pro Plan Hydra Care Sıvı Alımı Destekleyici Kedi Ek Besini", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 105, name: "Reflex Kuzu Etli Yavru Köpek Maması (1 kg)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 106, name: "Reflex Kompakt Kokusuz Kedi Kumu (10 kg)", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 107, name: "Matth Soslu Parçalı Tavuklu Yetişkin Kedi Konserve Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 108, name: "NutriCanin Tahılsız Kuzu ve Sığır Etli Köpek Konserve Maması (400 gr)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 109, name: "Garden Mix Ördekli Kedi Çorbası (40 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 110, name: "Kitten Genius Rewards Tahılsız Tavuklu ve Narlı Yavru Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 111, name: "NutriCanin Tahılsız Yaban Domuzlu Hipoalerjenik Yetişkin Köpek Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 112, name: "Advance Active Defense Tavuklu Yetişkin Kedi Maması (1-10 Yaş)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 113, name: "Reflex Soslu Kuzu Etli Yavru Kedi Konserve Maması (185 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 114, name: "Advance Active Defense Tavuklu Yavru Kedi Maması (2-12 Ay)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 115, name: "Purina Pro Plan Orta Irk Hassas Derili Yavru Köpek Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 116, name: "Kiki Excellent Lavanta Kokulu Kedi Kumu Koku Giderici", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 117, name: "Wanpy Tahılsız Fırınlanmış Parçacıklı Tavuklu Yetişkin Kedi Maması (1.5 kg)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 118, name: "Dreamies Shakeups Deniz Mahsullü Multivitaminli Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 119, name: "Pedigree Dentastix Günlük Ağız ve Diş Bakımı Köpek Ödülü (5-10 kg)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 120, name: "Fresh Paty pH Göstergeli Sağlık Kontrol Kedi Kumu", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 121, name: "Quik Ekstra Kalsiyumlu Mürekkep Balığı Kemiği", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 122, name: "Nutri Canin Doğal Ördekli ve Pres Derili Yüksek Proteinli Köpek Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 123, name: "Wanpy Ton Balıklı ve Karidesli Sıvı Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 124, name: "Garden Mix Tavuklu Kedi Çorbası (40 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 125, name: "Purina Pro Plan Küçük Irk Hassas Sindirim Yetişkin Köpek Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 126, name: "Garden Mix Somonlu Kedi Çorbası (40 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 127, name: "Super Premium Taze Somonlu Yavru Kedi Maması (2 kg)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 128, name: "Wanpy Ördekli ve Tavuklu Sıvı Kedi Ödülü (5'li Paket)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 129, name: "Wanpy Somonlu ve Tavuklu Sıvı Kedi Ödülü (5'li Paket)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 130, name: "Nutri Feline Doğal Somonlu Kedi Ödülü (50 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 131, name: "Advance Active Defense Orta Irk Kilo Kontrollü Diyet Köpek Maması (10-30 kg)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 132, name: "Wanpy Kuzu, Tavuk, Ördek, Havuç ve Bezelyeli Sıvı Kedi Ödül Ezmesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 133, name: "BioFeline Plus+B Multivitamin & Biotin Tüy Dökülme Karşıtı Kedi Macunu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 134, name: "Garden Mix Pick Stone Tüm Kuşlar İçin Gaga Taşı", category: "Kuş / Kemirgen", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 135, name: "BioFeline Probio Sıvı Probiyotik Sindirim Destekleyici", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 136, name: "Quik Doğal Kedi Çimi (Koruyucu File Hediyeli)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 137, name: "Wanpy Morina Balıklı ve Tavuklu Tüy Yumağı Kontrollü Sıvı Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 138, name: "Nutri Feline Kuzu Etli ve Kedi Otlu Doğal Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 139, name: "Nutri Canin Doğal Kuzu Etli & Burgu Derili Bağışıklık Destekli Köpek Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 140, name: "Motta Soslu Dana Etli Parçalı Yetişkin Köpek Konserve Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 141, name: "Kiki Excellent Okyanus Esintisi Kedi Kumu Koku Giderici", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 142, name: "Purina Pro Plan Kuzu Etli Orta Irk Hassas Sindirim Yavru Köpek Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 143, name: "Reflex Plus Somonlu Kedi Ödül Çubuğu", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 144, name: "Kiki Excellent Yasemin Kokulu Kedi Kumu Koku Giderici", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 145, name: "Matth Soslu Kuzu Etli Parçalı Yetişkin Kedi Konserve Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 146, name: "Nutri Feline Doğal Tavuklu ve Balıklı Sandviç Kedi Ödülü (50 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 147, name: "Acana Evde Yaşayan ve Kısırlaştırılmış Tavuklu & Ringa Balıklı Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 148, name: "SupraVet Profesyonel Çiş Eğitim Pedi (60 x 90 cm, 30 Adet)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 149, name: "Slim Lavanta Kokulu Kedi Kumu", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 150, name: "Purina Gourmet Gold Sığır Etli Soslu Yaş Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 151, name: "Wanpy Ton Balıklı ve Karidesli Sıvı Kedi Ödülü (5'li Paket)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 152, name: "Enjoy Soslu Tavuk Parçalı Yetişkin Kedi Konservesi (85 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 153, name: "Wanpy İdrar Yolu Sağlığı Destekli Ördek ve Tavuklu Sıvı Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 154, name: "Nutri Canin Kuzu Etli ve Kolajenli Köpek Ödül Çubuğu (80 gr)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 155, name: "Nutri Canin Ördek Etli ve Kolajenli Köpek Ödül Çubuğu (80 gr)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 156, name: "Felicia Derma+ Somonlu ve Patatesli Yetişkin Deri ve Tüy Destekli Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 157, name: "Felicia Hipoalerjenik Kuzu Etli Yetişkin Kedi Maması (1 kg)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 158, name: "Nutri Canin Tahılsız Sığır Etli Hipoalerjenik Yetişkin Köpek Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 159, name: "Reflex Plus Soslu Ördek ve Tavşan Etli Yetişkin Kedi Konservesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 160, name: "Royal Canin Anne ve Bebek Kedi Mus Konserve (1-4 Ay)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 161, name: "Royalist Evcil Hayvan Parfümü", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 162, name: "SupraVet Profesyonel Biotin, Çinko ve Omega 3 Deri-Tüy Desteği", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 163, name: "Les Repas Plaisir Morina Balıklı Kısırlaştırılmış Yetişkin Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 164, name: "Enjoy Soslu Kuzu Parçalı Yetişkin Kedi Konservesi (85 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 165, name: "Wanpy Fırınlanmış Yumuşak Somonlu ve Balık Derili Köpek Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 166, name: "Nutri Canin Sığır Etli ve Pres Derili Kalsiyum Destekli Köpek Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 167, name: "Nutri Canin Tahılsız Kuzu Etli Hipoalerjenik Yavru Köpek Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 168, name: "Nutri Canin Doğal Kuzu Etli Küp Köpek Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 169, name: "Wanpy Ördek, Tavuk, Havuç ve Bezelyeli Sıvı Kedi Ödül Ezmesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 170, name: "Wanpy Somon, Tavuk ve Havuçlu Sıvı Kedi Ödül Ezmesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 171, name: "Felicia Sindirim Sistemi Destekli Tavuklu Yetişkin Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 172, name: "Felicia Üriner Sistem Destekli Kısırlaştırılmış Yetişkin Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 173, name: "Ultra Premium Az Tahıllı Kuzu ve Somonlu Üriner Kısırlaştırılmış Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 174, name: "Loi Life Aktif Karbonlu Yeni Nesil Topaklanan Kedi Kumu", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 175, name: "Wanpy Ton Balıklı, Tavuklu ve Havuçlu Sıvı Kedi Ödül Ezmesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 176, name: "Wanpy Ördekli ve Balkabaklı Sıvı Kedi Ödül Ezmesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 177, name: "Wanpy Tavuklu ve Havuçlu Sıvı Kedi Ödül Ezmesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 178, name: "Nutri Canin Sığır Etli ve Kolajenli Köpek Ödül Çubuğu", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 179, name: "Ranova Dondurularak Kurutulmuş Tavuklu ve Balkabaklı Lolipop Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 180, name: "Royal Canin Mini Yetişkin Köpek Ezme Konserve (195 gr)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 181, name: "Garden Mix Ördek, Havuç ve Bezelyeli Sıvı Köpek Ödül Ezmesi", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 182, name: "Eastland Matatabi Kedi Oyuncağı", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 183, name: "Hill's Science Plan Tavuklu Kısırlaştırılmış Yavru Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 184, name: "Royal Canin Soslu Yavru Kedi Konserve Maması (85 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 185, name: "Ranova Dondurularak Kurutulmuş Karışık Lolipop Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 186, name: "Royal Canin Maxi Yetişkin Büyük Irk Köpek Maması (15 Ay Üzeri)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 187, name: "Royalist Aloe Veralı Pati Temizleme Köpüğü", category: "Kum / Kozmetik", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 188, name: "Wanpy Eklem Destekli Sığır Etli Sıvı Kedi Ödülü (5'li Paket)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 189, name: "Nutri Canin E Vitaminli Ördekli ve Kolajenli Köpek Ödül Çubuğu", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 190, name: "Royal Canin Mini Yetişkin Soslu Köpek Konserve Maması (10 kg'a kadar)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 191, name: "Pedigree Jumbone Mini Sığır ve Kümes Hayvanlı Köpek Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 192, name: "Royal Canin Kısırlaştırılmış Yetişkin Kedi Soslu İnce Dilimler Konserve", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 193, name: "Wanpy Deri ve Tüy Destekli Ton Balıklı ve Somonlu Sıvı Kedi Ödülü (5'li Paket)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 194, name: "Royal Canin Kilo Kontrollü Soslu İnce Dilimler Kedi Konservesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 195, name: "Royal Canin Kısırlaştırılmış Tüm Irklar İçin Köpek Konserve Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 196, name: "Royal Canin Chihuahua Yetişkin Köpek Mus Konserve", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 197, name: "Ranova Dondurularak Kurutulmuş Tavuklu ve Turna Yemişli Lolipop Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 198, name: "Felicia Tahılsız Tavuklu Kısırlaştırılmış Yetişkin Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 199, name: "Nutri Canin Sinirli Kuzu Etli ve Kolajenli Yumuşak Köpek Ödül Çubuğu", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 200, name: "Les Repas Plaisir Tavuklu Yetişkin Köpek Konserve Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 201, name: "Ranova Dondurularak Kurutulmuş Tavuklu ve Keçi Sütlü Lolipop Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 202, name: "Nutri Canin Doğal Ördek Etli Köpek Ödülü (80 gr)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 203, name: "Flexi Tape Şerit Otomatik Köpek Gezdirme Tasması Medium (5 Metre, maks. 25 kg)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 204, name: "Nutri Canin Doğal Kuzu Etli Şerit Köpek Ödülü (80 gr)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 205, name: "Les Repas Plaisir Bağırsak Sağlığı Destekli Soslu Tavuklu Kedi Konservesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 206, name: "Nutri Canin Kuzu Etli Kalsiyum ve E Vitaminli Burgu Diş Bakım Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 207, name: "Wanpy İçi Dolgulu Çıtır Tavuklu Kedi Ödülü (60 gr)", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 208, name: "Reflex Crunchy Bubbles Kuzu Etli Yetişkin Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 209, name: "Wanpy Tahılsız Fırınlanmış Kuzu Etli Yetişkin Kedi Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 210, name: "Wanpy Böbrek Sağlığı Destekli Tavuklu ve Sebzeli Sıvı Kedi Ödülü", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 211, name: "Nutri Canin Doğal Sığır Etli Köpek Ödülü (80 gr)", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 212, name: "Wanpy Kuzu Etli, Havuç ve Bezelyeli Sıvı Kedi Ödül Ezmesi", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 213, name: "Nutri Canin Tahılsız Ördekli ve Kolajenli Köpek Ödül Çubuğu", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 214, name: "Felicia Tahılsız Jöleli Kuzu Etli Yavru Kedi Konserve Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 215, name: "Felicia Tahılsız Jöleli Somonlu Kısırlaştırılmış Kedi Konserve Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 216, name: "Nutri Canin Tahılsız & Glutensiz Sığır Etli Yetişkin Köpek Maması", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 217, name: "Les Repas Plaisir Tavuklu Yavru Kedi Konserve Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 218, name: "Nutri Canin Tahılsız Sığır Etli ve Kedi Otlu Burgu Diş Bakım Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 219, name: "Nutri Canin Tahılsız Ördekli Burgu Diş Bakım Köpek Ödülü", category: "Köpek", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 220, name: "Felicia Tahılsız Jöleli Somonlu Yetişkin Kedi Konserve Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 221, name: "Wanpy Soslu Gerçek Tavuk ve Ördek Etli Yavru Kedi Konserve Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 222, name: "Felicia Tahılsız Jöleli Kuzu Etli Yetişkin Kedi Konserve Maması", category: "Kedi", price: 0, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },

  /* ─── DÜKKÂN VE TEZGÂH ÜRÜNLERİ (AÇIK MAMA, AKKUM, SUPREME, ANATOLIAN VB.) ─── */
  { id: 1788868772448, name: "Supreme Kıyılmış Tavuk Biftek", category: "Kedi", price: 35, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788868753596, name: "Supreme Kıyılmış Ton Balıklı Mus", category: "Kedi", price: 35, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788868712528, name: "Supreme Kıyılmış Tavuklu Uskumrulu", category: "Kedi", price: 35, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788868696150, name: "Supreme Kıyılmış Tavuklu Ton Balık", category: "Kedi", price: 35, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788868675953, name: "Supreme Kıyılmış Tavuk Mus", category: "Kedi", price: 35, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788868654079, name: "Supreme Kıyılmış Ördekli Somon", category: "Kedi", price: 35, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788868067469, name: "AÇIK Micho 1 kg", category: "Açık Mama", price: 165, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788868016569, name: "AÇIK Felicia Kısır Somon 1 kg", category: "Açık Mama", price: 350, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788868001791, name: "AÇIK Felicia Yetişkin Tavuk 1 kg", category: "Açık Mama", price: 350, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867985206, name: "AÇIK Felicia Yetişkin Somon 1 kg", category: "Açık Mama", price: 350, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867967123, name: "AÇIK Felicia Yetişkin Kuzu 1 kg", category: "Açık Mama", price: 350, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867931547, name: "Felicia Kitten Kuzu 1 kg", category: "Kedi", price: 350, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867907735, name: "Felicia Kitten Tavuk 1 kg", category: "Kedi", price: 350, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867786593, name: "Akkum Kalın Kokusuz 10 kg", category: "Kum / Kozmetik", price: 340, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867763073, name: "Akkum Kalın Sabun Kokulu 10 kg", category: "Kum / Kozmetik", price: 340, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867738198, name: "Akkum Kalın Pudra Kokulu 10 kg", category: "Kum / Kozmetik", price: 340, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867721864, name: "Akkum İnce Pudra Kokulu 10 kg", category: "Kum / Kozmetik", price: 340, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867570255, name: "Akkum İnce Sabun Kokulu 10 kg", category: "Kum / Kozmetik", price: 340, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867546787, name: "Akkum İnce Kokusuz 10 kg", category: "Kum / Kozmetik", price: 340, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867405996, name: "Anatolian Kitten Tavuk Pate 400 gr", category: "Kedi", price: 85, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867384535, name: "Anatolian Kısır Somon Pate 400 gr", category: "Kedi", price: 85, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867362572, name: "Anatolian Somon Pate 400 gr", category: "Kedi", price: 85, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867324448, name: "Anatolian Tavuk Pate 400 gr", category: "Kedi", price: 85, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788867302299, name: "Anatolian Kuzu 400 gr Pate", category: "Kedi", price: 85, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788856842402, name: "AÇIK Royal Canin Kısır 1 kg", category: "Açık Mama", price: 600, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788884802113, name: "Pro Plan Yaş Mama Kısır Ton Balığı 85 gr", category: "Kedi", price: 70, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788884422358, name: "Kuş Kafesi Tülü", category: "Kuş / Kemirgen", price: 50, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788884045195, name: "Elekli Paspas", category: "Kum / Kozmetik", price: 200, cost: 0, vatRate: 20, stock: 1, supplier: "-", batches: [] },
  { id: 1788883731401, name: "Kedi Tuvaleti Küçük Boy", category: "Kum / Kozmetik", price: 650, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788883571561, name: "AÇIK Royal Canin Sensible 1 kg", category: "Açık Mama", price: 600, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788881627839, name: "Motto Kedi Yaş Mama 3 Tane", category: "Kedi", price: 160, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788881586006, name: "Garden Mix Darı", category: "Kuş / Kemirgen", price: 250, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] },
  { id: 1788880048112, name: "Tekli Kemik", category: "Köpek", price: 10, cost: 0, vatRate: 20, stock: 0, supplier: "-", batches: [] }
];

var catalogProducts = window.catalogProducts;

